### ISSUE TITLE
Source code for pgxman

### ISSUE THREAD

**Issue by ibotty** [pgxman/buildkit#21]
Hi,

what's pgxman's license and where can I find the source code (if it is, as I assume, Open Source).

Thank you.

**Comment by owenthereal** [comment]
@ibotty I'm glad you found this repo. We are in the process of open sourcing pgxman. Please stay tuned for more info 😄 .

**Comment by ibotty** [comment]
Thank you for the reply.

**Comment by owenthereal** [comment]
See https://github.com/pgxman/pgxman 😄
